name: Rust-CICD

on:
  push:
    branches: [ "master", "dev", "4-cicd-deployment-pipeline" ]
  pull_request:
    branches: [ "master", "dev", "4-cicd-deployment-pipeline" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build
    #   run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
